import type { Metadata } from "next";
import './globals.css'
import AppHeader from "@/components/app.header";
import AppFooter from "@/components/app.footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <header>
            <AppHeader />
          </header>
          {children}
          <footer>
            <AppFooter />
          </footer>
        </div>
      </body>
    </html>
  );
}
